version: "3.8"

services:
  app:
    image: phillisapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3001:3000"

  db:
    image: mongo
